version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.2.0
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      FLYWAY_USER: myuser
      FLYWAY_PASSWORD: mypassword
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./flyway/sql:/flyway/sql
    command: [ "migrate" ]
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://db:5432/postgres"
      DB_USER: myuser
      DB_PASSWORD: mypassword
    command: [ "./wait-for-it.sh", "db:5432", "--", "java", "-jar", "/app/app.jar"]
    depends_on:
      flyway:
        condition: service_completed_successfully

volumes:
  postgres_data:
